In [1]:
import tensorflow as tf

In [2]:
a = tf.placeholder(tf.float32, shape=(None, 3))

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [7]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 


In [25]:
tf.reset_default_graph()
x = tf.placeholder(tf.float32, (None))
y = x + 6

with tf.Session() as sess:
    y_val_1 = y.eval(feed_dict={x:[[1, 2, 3]]})
    y_val_2 = y.eval(feed_dict={x:[[1, 2, 3], [3, 4, 1]]})

In [26]:
print(y_val_1)

[[7. 8. 9.]]


In [27]:
print(y_val_2)

[[ 7.  8.  9.]
 [ 9. 10.  7.]]
