In [61]:
import numpy as np
import gym
import random
import matplotlib.pyplot as plt
import time
from IPython.display import clear_output

In [69]:
class Agent:
    def __init__(self, env):
        
        # Initializing Agent/Sim parameters
        self.q_table = np.zeros((env.observation_space.n, env.action_space.n))
        
        self.alpha = 0.9 # learning rate
        self.gamma = 0.96 # discount factor
        self.epsilon = 0.85 # exploration rate
        self.action = None
        
        self.current_state = env.reset()
        
        self.n_episodes = 100000 # Episodes to play
        self.n_steps = 200 # Max steps in an episode
        
    def learn(self, new_state, reward):
        self.reward = reward
        
        # The Bellman Equation
        self.q_table[self.current_state, self.action] = self.q_table[self.current_state, self.action] + \
        self.alpha*(reward + self.gamma*np.max(self.q_table[new_state, :]) - \
                    self.q_table[self.current_state, self.action])
        
    def selectAction(self):
        if(random.uniform(0, 1) < self.epsilon):
            return env.action_space.sample()
        else:
            return np.argmax(self.q_table[self.current_state, :])
        
    def updateParameters(self):        
        self.epsilon = np.maximum(self.epsilon - 0.05, 0.1)
        #self.alpha = np.maximum(self.alpha - 0.05, 0.6)

In [70]:
env = gym.make("Taxi-v3")
agent = Agent(env)

state in constructor:  324


In [66]:
# Random play
env.reset()

for i in range(100):
    action = env.action_space.sample()
    state, reward, done, info = env.step(action)
    env.render()
    if(done):
        break
    time.sleep(0.01)
    clear_output(wait=True)

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)


In [ ]:
#agent = Agent(env)

for i in range(agent.n_episodes):
    agent.state = env.reset()
    for j in range(agent.n_steps):        
        
        agent.action = agent.selectAction()
        state, reward, done, info = env.step(agent.action)
        agent.learn(state, reward)
        agent.current_state = state

        env.render()
        
        if(done):
            break
        print("Current episode number: ", i)
        print(agent.q_table)
        time.sleep(0.01)
        clear_output(wait=True)
    
    #if ((i%10000) == 0):
        #agent.updateParameters()


+---------+
|R: | : :G|
| : | : : |
| : : :_: |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
Current episode number:  72
[[ 0.86453169  0.20384641  7.95175663  6.08683912 -5.5496862  -5.89885267]
 [ 7.15224231  8.22858169  8.34252119  8.28103751  8.43842454  0.08950749]
 [16.75404215 17.33891787 17.43637545 18.72782342 15.66838841  7.98059756]
 ...
 [14.068989   15.63657473 14.05395986 14.5294897   5.24496679  5.62064332]
 [11.2838494  13.10818167 11.39677662 13.27545378  2.55132297  2.41069766]
 [21.38623928 19.51220656 21.52621611 29.30643375 12.5269019  12.5540499 ]]


In [68]:
print(agent.epsilon, agent.alpha)

0.34999999999999976 0.6
