In [75]:
import numpy as np
import gym
import random
import matplotlib.pyplot as plt
import time
from IPython.display import clear_output
import pickle

In [69]:
class Agent:
    def __init__(self, env):
        
        # Initializing Agent/Sim parameters
        self.q_table = np.zeros((env.observation_space.n, env.action_space.n))
        
        self.alpha = 0.9 # learning rate
        self.gamma = 0.96 # discount factor
        self.epsilon = 0.85 # exploration rate
        self.action = None
        
        self.current_state = env.reset()
        
        self.n_episodes = 100000 # Episodes to play
        self.n_steps = 200 # Max steps in an episode
        
    def learn(self, new_state, reward):
        self.reward = reward
        
        # The Bellman Equation
        self.q_table[self.current_state, self.action] = self.q_table[self.current_state, self.action] + \
        self.alpha*(reward + self.gamma*np.max(self.q_table[new_state, :]) - \
                    self.q_table[self.current_state, self.action])
        
    def selectAction(self):
        if(random.uniform(0, 1) < self.epsilon):
            return env.action_space.sample()
        else:
            return np.argmax(self.q_table[self.current_state, :])
        
    def updateParameters(self):        
        self.epsilon = np.maximum(self.epsilon - 0.05, 0.1)
        #self.alpha = np.maximum(self.alpha - 0.05, 0.6)

In [70]:
env = gym.make("Taxi-v3")
agent = Agent(env)

state in constructor:  324


In [66]:
# Random play
env.reset()

for i in range(100):
    action = env.action_space.sample()
    state, reward, done, info = env.step(action)
    env.render()
    if(done):
        break
    time.sleep(0.01)
    clear_output(wait=True)

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)


In [74]:
#agent = Agent(env)
agent.epsilon = 0.1
for i in range(100):
    agent.state = env.reset()
    for j in range(agent.n_steps):        
        
        agent.action = agent.selectAction()
        state, reward, done, info = env.step(agent.action)
        agent.learn(state, reward)
        agent.current_state = state

        env.render()
        
        if(done):
            break
        print("Current episode number: ", i)
        print(agent.q_table)
        time.sleep(0.1)
        clear_output(wait=True)
    
    #if ((i%10000) == 0):
        #agent.updateParameters()


+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)


In [68]:
print(agent.epsilon, agent.alpha)

0.34999999999999976 0.6


In [78]:
pickle_out = open("pickled_qtable.pkl","wb")
pickle.dump(agent.q_table, pickle_out)
pickle_out.close()

In [79]:
pickle_in = open("pickled_qtable.pkl","rb")
example_dict = pickle.load(pickle_in)

In [80]:
type(example_dict)

numpy.ndarray

In [81]:
print(example_dict)

[[ 4.75905748  1.11739268  2.76596329  0.62057501 -6.2195181  -3.9105127 ]
 [ 8.24653574  8.97905968  9.10075603  9.15276327 12.98027437  0.11345978]
 [ 9.87998663 13.47338384  9.9910746  13.47343592 16.15595384  6.69258676]
 ...
 [16.27997343 17.15452872 15.96769626 16.19991682 10.41536245 10.37956566]
 [ 8.60779808 11.24569441  7.27693761  7.06592653 -0.53239845 -0.52029961]
 [21.88319926 20.02856888 22.0390101  24.76745993 14.6497005  14.59838742]]
